### ISSUE TITLE
IndexError: list index out of range (simulation branch)

### ISSUE THREAD

**Issue by synctext** [michael-the1/tsukiji#12]
python simu.py
Starting simulation..
Traceback (most recent call last):
  File "simu.py", line 49, in <module>
    simulate()
  File "simu.py", line 43, in simulate
    allocate_msgs()
  File "simu.py", line 28, in allocate_msgs
    orders = get_orders()
  File "simu.py", line 19, in get_orders
    if not row[0] == 'T':
IndexError: list index out of range

When using as input semi-random data as:
```
<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
```

**Comment by Yuugoh** [comment]
This occured because wget retrieved the wrong file. Orderlist.csv is now no longer ignored by git, solving this issue.
